from __future__ import annotations

import json
from pathlib import Path
from typing import Any


def pick_supported_candidate(
    analysis_dict: dict[str, Any],
    *,
    object_type: str,
    contains_text: str | None = None,
) -> dict[str, Any]:
    contains_text_lower = contains_text.lower() if contains_text else None

    supported_keys = [
        group["repeatKey"]
        for group in analysis_dict["repeatGroups"]
        if group["removability"] == "supported" and group.get("objectType") == object_type
    ]

    for page in sorted(analysis_dict["candidatesByPage"], key=lambda p: int(p)):
        for candidate in analysis_dict["candidatesByPage"][page]:
            if candidate.get("objectType") != object_type:
                continue
            if contains_text_lower is not None:
                if contains_text_lower not in candidate.get("text", "").lower():
                    continue
            if candidate.get("repeatKey") in supported_keys:
                return candidate

    raise AssertionError(
        f"No supported candidate found for object_type={object_type!r} "
        f"contains_text={contains_text!r}"
    )


def build_plan_from_candidate(
    *,
    source_file_name: str,
    candidate: dict[str, Any],
    target_pages: list[int],
    removability: str | None = None,
) -> dict[str, Any]:
    selected_candidate = {
        "id": candidate["id"],
        "pageNumber": candidate["pageNumber"],
        "objectType": candidate["objectType"],
        "label": candidate["label"],
        "repeatKey": candidate["repeatKey"],
        "confidence": candidate["confidence"],
        "removability": removability or candidate.get("removability", "supported"),
    }

    if candidate.get("objectType") == "image_xobject":
        selected_candidate["imageIdentityKey"] = candidate.get("imageIdentityKey")
        selected_candidate["resourceName"] = candidate.get("resourceName")

    return {
        "planVersion": "1.0",
        "createdAt": "2026-04-20T00:00:00Z",
        "sourceFileName": source_file_name,
        "selectedCandidate": selected_candidate,
        "scope": {
            "mode": "all",
            "targetPages": target_pages,
            "strategy": "all_matching_repeat_key",
        },
        "preferredEngines": ["pikepdf", "PyMuPDF"],
        "preservationGoal": "Preserve page appearance as much as possible.",
        "engineHints": ["text_run and image_xobject only"],
        "riskLevel": "low",
        "notes": ["generated by tests"],
    }


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=True),
        encoding="utf-8",
    )
